### ISSUE TITLE
Export to Diagrams.net not working

### ISSUE THREAD

**Issue by hetul99** [aws-solutions/workload-discovery-on-aws#382] opened 2023-02-02 19:39 UTC
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

When I select the Diagrams.net (formerly Draw.io) radio button and click 'Export,' it gives following error:
`unsupported operand type(s) for *: 'NoneType' and 'float'`
PFA
---

**Describe the bug**
A description of what the bug is.
N/A

**To Reproduce**

1. Go to 'Diagrams > Manage'
2. Click on Diagram generated
3. Actions > Diagram > Export
4. Select Diagrams.net (formerly Draw.io) > Export
5. This will give error after few seconds: unsupported operand type(s) for *: 'NoneType' and 'float'

**Expected behavior**
A description of what you expected to happen.
It should provide an io diagram that gets open in new tab from where we can save it as pdf

**Screenshots**
![image](https://user-images.githubusercontent.com/46005122/216432519-043d31f2-5dc0-4bb1-b681-c526beafe26c.png)

**Browser (please complete the following information):**

- Name: Chrome
- Chrome is up to date
Version 109.0.5414.120 

**Additional context**

**Comment by svozza** [comment] 2023-02-02 20:42
this is a duplicate of #329. We are working on a fix for v2.1.0.

**Closed** 2023-02-02 20:45 UTC
Labels: bug
