### ISSUE TITLE
Inaccurate cost information 

### ISSUE THREAD

**Issue by luketk05** [aws-solutions/workload-discovery-on-aws#445] opened 2023-08-04 20:38 UTC
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

The estimated cost in workload discovery is roughly double the actual billed amount. I have tested this across four different accounts and I am currently on version 2.0.3.

**To Reproduce**

1. Follow the instructions to set up the costing feature and bucket replication 
2. Log into the Workload Discovery console
3. Go to "Costs"
4. Select an account ID 
5. In "Cost Data Time Period" enter the timeframe for the entire last month
6. Note the Estimated Cost (In my case 6699.76)
7. Login to the corresponding account
8. In the AWS console navigate to the billing console
9. Go to "Bills"
10. In the upper-right corner select the previous month
11. The returned bill will be very different from the estimated cost (In my case 3365.10)

**Expected behavior**
I expect the estimated value to be closer to the actual billed amount

**Screenshots**

**Browser (please complete the following information):**

- Name chrome
- Version 115.0.5790.110

**Additional context**

**Comment by svozza** [comment] 2023-08-21 13:24
Hi there,
I have tried reproducing this on the latest version of our code base and have been unable to. The code for the cost feature has changed a bit for the upcoming release (v2.1.0) so it may have been fixed by that. We are aiming to release by the end of Q3 but this date could slip. I will update this ticket when the release has happened to let you know.

**Comment by svozza** [comment] 2023-12-20 17:04
We fixed several bugs in the cost feature in v2.1.3 that was released yesterday, I wonder if that might fix this issue.

**Comment by gitcdb** [comment] 2024-01-08 15:52
@svozza  the costs still look to be quite off. I was hoping maybe it's the Savings Plans or Enterprise Support costs, but subtracted from the account total, the remainder is less than Workload Discovery displays for costs. Any thoughts on what would account for the discrepancy? 

Screenshots attached: 

![Screenshot 2024-01-08 at 07 47 32](https://github.com/aws-solutions/workload-discovery-on-aws/assets/49329875/8735a8ee-3097-412f-a5db-e17ea9c04ce0)
![Screenshot 2024-01-08 at 07 47 18](https://github.com/aws-solutions/workload-discovery-on-aws/assets/49329875/5f1686e8-e225-48ff-826b-6db9c0de263f)

**Comment by svozza** [comment] 2024-01-22 17:47
Sorry, I didn't see this reply. The solution doesn't take savings plans into account, could that be the cause of the discrepency?

**Comment by shujacks** [comment] 2024-04-10 17:03
Hi gitcdb please take a look at the the above question and let us know. If we don't hear from you soon I will close the issue, thanks.

**Closed** 2024-04-19 08:27 UTC
Labels: bug
