### ISSUE TITLE
Select All 

### ISSUE THREAD

**Issue by FirasBW** [aws-solutions/workload-discovery-on-aws#461] opened 2023-10-08 07:22 UTC
Select All

**Describe the feature you'd like to see implemented**
Alternative for selecting resources when building the digram (in our case we gate arroung 200 pages have to be selected  )

**Describe the value this feature will add to AWS Perspective**
Simplify the way to select all the resources instead of flip the pages to select

**Comment by svozza** [comment] 2023-10-09 15:50
Closing as a duplicate of  #338.

**Closed by svozza** 2023-10-09 15:50 UTC
Labels: enhancement
