### ISSUE TITLE
JSON Export not responding

### ISSUE THREAD

**Issue by mikeoterog** [aws-solutions/workload-discovery-on-aws#394] opened 2023-03-06 18:23 UTC
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
JSON not responding while trying to export

**To Reproduce**

1. Go to Workload Discovery on AWS Dashboard
2. Click on Diagrams -> Manage
3. Select the Diagram to export
4. Nothing happens

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment] 2023-03-06 18:25
This is a duplicate of https://github.com/aws-solutions/workload-discovery-on-aws/issues/336.

**Closed** 2023-03-09 14:02 UTC
Labels: bug, duplicate
