### ISSUE TITLE
JSON export not working

### ISSUE THREAD

**Issue by jhormigo** [aws-solutions/workload-discovery-on-aws#426] opened 2023-05-19 13:14 UTC
**Describe the bug**
Click export and then JSON -> EXPORT BUTTON -> The JSON never downloads

**To Reproduce**

1. Go to 'url/diagrams/private/nameofdiagram/export'
2. Click on 'JSON'
3. Click on Export
4. Nothing happens

**Expected behavior**
It should download the JSON

**Browser (please complete the following information):**

- Name chrome, firefox, safari

**Comment by svozza** [comment] 2023-05-19 13:16
This is a duplicate of https://github.com/aws-solutions/workload-discovery-on-aws/issues/336. It will be fixed in the 2.1.0 release.

**Closed** 2023-09-25 21:16 UTC
Labels: bug
